spring:
  datasource:
    url: jdbc:mysql://customer-app-mysql:3306/customerdb
    username: root
    password: root
    initialization-mode: always 

  jpa:
    show-sql: true
    
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none


management:
  endpoints:
    web: 
      exposure:
        include:
        - "*" 
    
server:
  port: 8080
  
logging:
  file:
    name: customer.log
    path: ../logs
    
    